---
title: HTTP
tags:
 - protocol
 - L7
---


[RFCs]
- rfc:1945[] - HTTP/1.0
- rfc:7230[] - HTTP/1.1: Message Syntax and Routing
- rfc:7231[] - HTTP/1.1: Semantics and Content
- rfc:7232[] - HTTP/1.1: Conditional Requests
- rfc:7233[] - HTTP/1.1: Range Requests
- rfc:7234[] - HTTP/1.1: Caching

---

== response status codes

[%header,format=csv, cols="1,3"]
|===
response type,response code range
informational responses,100–199
successful responses,200–299
redirects,300–399
client errors,400–499
server errors,500–599
|===

RFC 7231 contains a list of error codes in HTTP/1.1 (the current standard) in https://tools.ietf.org/html/rfc7231#section-6.1[section 6.1].

[%header,format=csv, cols="1,2,6"]
|===
code,meaning,source
100,Continue,https://tools.ietf.org/html/rfc7231#section-6.2.1            
101,Switching Protocols,https://tools.ietf.org/html/rfc7231#section-6.2.2            
200,OK,https://tools.ietf.org/html/rfc7231#section-6.3.1            
201,Created,https://tools.ietf.org/html/rfc7231#section-6.3.2            
202,Accepted,https://tools.ietf.org/html/rfc7231#section-6.3.3            
203,Non-Authoritative Information,https://tools.ietf.org/html/rfc7231#section-6.3.4            
204,No Content,https://tools.ietf.org/html/rfc7231#section-6.3.5            
205,Reset Content,https://tools.ietf.org/html/rfc7231#section-6.3.6            
206,Partial Content,https://tools.ietf.org/html/rfc7233#section-4.1 
300,Multiple Choices,https://tools.ietf.org/html/rfc7231#section-6.4.1            
301,Moved Permanently,https://tools.ietf.org/html/rfc7231#section-6.4.2            
302,Found,https://tools.ietf.org/html/rfc7231#section-6.4.3            
303,See Other,https://tools.ietf.org/html/rfc7231#section-6.4.4            
304,Not Modified,https://tools.ietf.org/html/rfc7232#section-4.1 
305,Use Proxy,https://tools.ietf.org/html/rfc7231#section-6.4.5            
307,Temporary Redirect,https://tools.ietf.org/html/rfc7231#section-6.4.7            
400,Bad Request,https://tools.ietf.org/html/rfc7231#section-6.5.1            
401,Unauthorized,https://tools.ietf.org/html/rfc7235#section-3.1
402,Payment Required,https://tools.ietf.org/html/rfc7231#section-6.5.2            
403,Forbidden,https://tools.ietf.org/html/rfc7231#section-6.5.3            
404,Not Found,https://tools.ietf.org/html/rfc7231#section-6.5.4            
405,Method Not Allowed,https://tools.ietf.org/html/rfc7231#section-6.5.5            
406,Not Acceptable,https://tools.ietf.org/html/rfc7231#section-6.5.6            
407,Proxy Authentication Required,https://tools.ietf.org/html/rfc7235#section-3.2 
408,Request Timeout,https://tools.ietf.org/html/rfc7231#section-6.5.7            
409,Conflict,https://tools.ietf.org/html/rfc7231#section-6.5.8            
410,Gone,https://tools.ietf.org/html/rfc7231#section-6.5.9            
411,Length Required,https://tools.ietf.org/html/rfc7231#section-6.5.10           
412,Precondition Failed,https://tools.ietf.org/html/rfc7232#section-4.2 
413,Payload Too Large,https://tools.ietf.org/html/rfc7231#section-6.5.11           
414,URI Too Long,https://tools.ietf.org/html/rfc7231#section-6.5.12           
415,Unsupported Media Type,https://tools.ietf.org/html/rfc7231#section-6.5.13           
416,Range Not Satisfiable,https://tools.ietf.org/html/rfc7233#section-4.4 
417,Expectation Failed,https://tools.ietf.org/html/rfc7231#section-6.5.14           
426,Upgrade Required,https://tools.ietf.org/html/rfc7231#section-6.5.15           
500,Internal Server Error,https://tools.ietf.org/html/rfc7231#section-6.6.1            
501,Not Implemented,https://tools.ietf.org/html/rfc7231#section-6.6.2            
502,Bad Gateway,https://tools.ietf.org/html/rfc7231#section-6.6.3            
503,Service Unavailable,https://tools.ietf.org/html/rfc7231#section-6.6.4            
504,Gateway Timeout,https://tools.ietf.org/html/rfc7231#section-6.6.5            
505,HTTP Version Not Supported,https://tools.ietf.org/html/rfc7231#section-6.6.6 
|===


